//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootShop.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int ProductID { get; set; }
        public string Article { get; set; }
        public int ProductNameID { get; set; }
        public string Unit { get; set; }
        public decimal Price { get; set; }
        public int ProviderID { get; set; }
        public int ManufacturerID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> Discount { get; set; }
        public int QuantityInStok { get; set; }
        public string Description { get; set; }
        public string PhotoFileName { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual ProductNames ProductNames { get; set; }
        public virtual Providers Providers { get; set; }
    }
}
